# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# Don't edit manually! Use `build.bat version` command instead!
version: 0.2.0-build-0{build}

os: Visual Studio 2015

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# branches to build
branches:
  # whitelist
  only:
    - main
    - dev

shallow_clone: true

cache:
  - packages
  
nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script: build.bat pack

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: GitHub
    auth_token:
      secure: Kx+tJBMfq/OK7sMpvQDdigFOIIfzYkVmIHxNQetanQdIA5Mb8zm/VhAkrId4x5zW
    artifact: /.*\.zip/
    draft: true
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    skip_symbols: true
    api_key: 
      secure: 8BQmcR1hP9MoxvrmXJKMtlRyX6LI36H9ZTU8fSEetvzMGCl1PUlXKZRUGq+GVMja
    on:
      appveyor_repo_tag: true
