# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Please don't edit it manually, use the `build.bat version` command instead.
version: 0.3.0-build-0{build}

os: Visual Studio 2022

# environment variables
environment:
  SIGNPATH_API_TOKEN:
    secure: ubV7KG4p0ySGWWWx1QuwxiMtJoUrib39HZNmNjiOxwss8xoRJgC0HGlkouSLSAdZ

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - ps: Install-Module -Name SignPath

# to run your custom scripts instead of automatic MSBuild
build_script: build.bat sign

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: 8BQmcR1hP9MoxvrmXJKMtlRyX6LI36H9ZTU8fSEetvzMGCl1PUlXKZRUGq+GVMja
    on:
      appveyor_repo_tag: true
